version: '3.8'

services:
  postgres:
    build:
      context: ./Juntin.Application/Dockerfiles
      dockerfile: PostgreDockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: juntin
    networks:
      - juntin_network

  redis:
    build:
      context: ./Juntin.Application/Dockerfiles
      dockerfile: RedisDockerfile
    networks:
      - juntin_network

networks:
  juntin_network:
    external: true