version: '3.8'

services:
  juntin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    networks:
      - juntin_network

networks:
  juntin_network:
    external: true